### ISSUE TITLE
Random Quote Generator

### ISSUE THREAD

**Issue by Baba-Yaga-1** [Tamanna-S/javaScript-projects#21]
I am a hacktoberfest contributor.
Can you assign me this issue ?

**Comment by aditi018** [comment]
I would like to work on this. Can you assign me this issue?

**Comment by Tamanna-S** [comment]
@Baba-Yaga-1 and @aditi018 you both can contribute but make sure to read the contribution guide and name your folder as stated!😄

**Comment by aditi018** [comment]
Created the pull request for the Random Quote Generator https://github.com/Tamanna-S/javaScript-projects/pull/33#issue-1396477032

**Comment by Baba-Yaga-1** [comment]
> @Baba-Yaga-1 and @aditi018 you both can contribute but make sure to read the contribution guide and name your folder as stated!😄

Okay.
