### ISSUE TITLE
Community Standards Checklist

### ISSUE THREAD

**Issue by Ayush-Kanduri** [Tamanna-S/javaScript-projects#35]
Hey Tamanna. 

Can I add the Code Of Conduct File, License, Issue Template, & Pull Request Template to the repository to complete the overall checklist of the community standards inside the insights?

**Comment by Tamanna-S** [comment]
yes read the contribution guide and create accordingly!

**Comment by Ayush-Kanduri** [comment]
> yes read the contribution guide and create accordingly!

Sure. Thanks for assigning.
