### ISSUE TITLE
add hover effect on the button. (beginner friendly)

### ISSUE THREAD

**Issue by Tamanna-S** [Tamanna-S/javaScript-projects#39]
add hover effect in this project
https://github.com/Tamanna-S/javaScript-projects/tree/main/basic-projects/Tamanna-S-todo-app

**Comment by Tatshree** [comment]
please assign this issues to me

**Comment by KaifKhan7393** [comment]
@Tamanna-S  assign it to me so I can work on it.

**Comment by Tamanna-S** [comment]
@KaifKhan7393 as @Tatshree  asked for it first so wait i wil be adding more issues.

**Comment by Tamanna-S** [comment]
@Tatshree go for it!
