### ISSUE TITLE
add some nice hover effects in rock-paper-scissors

### ISSUE THREAD

**Issue by Tamanna-S** [Tamanna-S/javaScript-projects#50]
please collab with @Tatshree as she is styling this.
here:
https://github.com/Tamanna-S/javaScript-projects/tree/main/intermediate-projects/Tamanna-S-rock-paper-scissors

**Comment by Vanshika2063** [comment]
assign to me

**Comment by vilasrhegde** [comment]
Can I look into this issue? and I am sure I can solve this one quickly.
