### ISSUE TITLE
write some css.

### ISSUE THREAD

**Issue by Tamanna-S** [Tamanna-S/javaScript-projects#71]
create red-text, yellow-text and green-text classes in style.css in which just write `color: <class-name>` and that's it!

here:
https://github.com/Tamanna-S/javaScript-projects/tree/main/intermediate-projects/Tamanna-S-rock-paper-scissors

**Comment by Vanshika2063** [comment]
can you please  assign to me?

**Comment by Tamanna-S** [comment]
sure!
